### ISSUE TITLE
Function name clash

### ISSUE THREAD

**Issue by markNZed** [UCD4IDS/ContinuousWavelets.jl#21]
Hi, it looks like Wavelets has implemented undocumented cwt and computeWavelets so the example needs to qualify those functions. It is great to have this package available - thanks!

**Comment by dsweber2** [comment]
I was one of the people responsible for those functions in Wavelets.jl, but decided to separate them out for easier maintenance. There's an active pull request to remove them, so this should eventually resolve on Wavelet.jl's side. I suppose in the meantime I should include the necessary qualifications in the docs.

Glad to hear someone's finding use in this package!

**Comment by henry2004y** [comment]
I guess the maintainer of `Wavelets.jl` is waiting for this package to become more stable for this https://github.com/JuliaDSP/Wavelets.jl/pull/70 to be merged. I don't know how much overlap these two packages have right now.
