### ISSUE TITLE
Error in README demo

### ISSUE THREAD

**Issue by henry2004y** [UCD4IDS/ContinuousWavelets.jl#26]
The first example in README returns error because 

```julia
julia> freqs = getMeanFreq(computeWavelets(n, c)[1])
WARNING: both ContinuousWavelets and Wavelets export "computeWavelets"; uses of it in module Main must be qualified
ERROR: UndefVarError: computeWavelets not defined
```

I guess this indicates that this package is still during the transition phase? One quick fix would be

```julia
freqs = getMeanFreq(ContinuousWavelets.computeWavelets(n, c)[1])
```

**Comment by dsweber2** [comment]
this is actually a consequence of https://github.com/UCD4IDS/ContinuousWavelets.jl/issues/21, which I'm a bit surprised the pull request hasn't been accepted yet in Wavelets.jl. I guess this is going to be necessary long term.
