### ISSUE TITLE
Spelling error on mothers.svg

### ISSUE THREAD

**Issue by BoundaryValueProblems** [UCD4IDS/ContinuousWavelets.jl#38]
There is a spelling error in one of the wavelet plots in docs/mothers.svg.
The mother wavelet function at the upper right is spelled as "Beylkyin". But the correct spelling is "Beylkin".
Please fix this minor typo.

**Comment by dsweber2** [comment]
Turns out I hadn't switched the github page to using the version in the docs, where I'd fixed. Its correct now
