### ISSUE TITLE
Wrong comment?

### ISSUE THREAD

**Issue by kosukesando** [UCD4IDS/ContinuousWavelets.jl#52]
The [comment here](https://github.com/UCD4IDS/ContinuousWavelets.jl/blob/dbb242b9cf6749a78f79a5672e6df12796622d88/src/waveletTypes.jl#L2) says 5.8 is the default for sigma but it seems that [`Morlet() = Morlet(2pi)` ](https://github.com/UCD4IDS/ContinuousWavelets.jl/blob/dbb242b9cf6749a78f79a5672e6df12796622d88/src/waveletTypes.jl#L16) defines that the default is 2pi?

**Comment by dsweber2** [comment]
thanks for the catch!
