### ISSUE TITLE
remove Wavelets 0.9 from dependecies?

### ISSUE THREAD

**Issue by AdamWysokinski** [UCD4IDS/ContinuousWavelets.jl#58]
Is it possible to remove Wavelets 0.9 from dependencies? It's a complex problem, but it causes an issue with ComplexityMeasures.jl ?
ATB, Adam

**Comment by dsweber2** [comment]
Could you elaborate a bit? When I look at the [complexityMeasures](https://github.com/JuliaDynamics/ComplexityMeasures.jl/blob/main/Project.toml) `project.toml`, it has exactly the same relationship with Wavelets.jl as this package does (both have wavelets between 0.9 and 0.10)?

**Comment by AdamWysokinski** [comment]
Oh, they must have corrected it recently. Sorry for bothering you.
